@echo off
echo Disabling strict SSL...
call npm config set strict-ssl false
echo Clearing cache...
call npm cache clean --force
echo Installing...
call npm install --verbose > install_log.txt 2>&1
echo Done.
